import type { DbEngine } from '../models';
import {
  formatQualifiedTable,
  type QualifiedTable,
  quoteQualifiedTable,
  quoteSqlIdentifier,
} from './identifiers';

/**
 * DDL for the table designer.
 *
 * Every statement here changes structure, so nothing is generated from a name
 * that has not been through quoteSqlIdentifier. Types and defaults are the one
 * exception: a column type is a dialect expression, not an identifier, and a
 * default is an expression too — `now()` and `0` are not the text of
 * themselves. Both are shown to the user in the generated SQL before anything
 * runs, which is what the designer's preview is for.
 *
 * The engines diverge more here than anywhere else in this app, so each
 * builder switches rather than pretending one dialect covers them all.
 */

export interface DesignerColumn {
  name: string;
  /** A dialect type expression: `varchar(64)`, `numeric(6,2)`, `text`. */
  dataType: string;
  nullable: boolean;
  /** A default *expression*, interpolated unquoted. Omit for none. */
  defaultValue?: string | null;
  primaryKey?: boolean;
  autoIncrement?: boolean;
}

const ENGINES: DbEngine[] = ['mysql', 'mariadb', 'postgres', 'mssql', 'oracle', 'sqlite'];

function assertEngine(engine: DbEngine): void {
  if (!ENGINES.includes(engine)) throw new Error(`Unsupported engine: ${engine}`);
}

function assertColumns(columns: DesignerColumn[] | string[], what: string): void {
  if (!columns || !columns.length) {
    throw new Error(`${what} needs at least one column.`);
  }
}

/** The identity/auto-increment clause, where the engine has one. */
function autoIncrementClause(engine: DbEngine): string {
  switch (engine) {
    case 'mysql':
    case 'mariadb': return ' AUTO_INCREMENT';
    case 'mssql': return ' IDENTITY(1,1)';
    // Postgres 10+ and Oracle 12c+ both took the SQL standard spelling.
    case 'postgres':
    case 'oracle': return ' GENERATED BY DEFAULT AS IDENTITY';
    // SQLite's is written inline after PRIMARY KEY — see columnClause.
    default: return '';
  }
}

/**
 * True for a SQLite column that has to be spelled `INTEGER PRIMARY KEY
 * AUTOINCREMENT` inline.
 *
 * That exact phrase is the alias for the rowid. Declaring the key as a
 * separate table-level constraint instead makes it an ordinary unique index,
 * and AUTOINCREMENT is not legal there at all.
 */
function isSqliteRowidKey(engine: DbEngine, column: DesignerColumn): boolean {
  return engine === 'sqlite' && Boolean(column.primaryKey) && Boolean(column.autoIncrement);
}

/**
 * One column as it appears inside CREATE TABLE or after ADD/MODIFY.
 *
 * Order matters: SQL Server rejects DEFAULT after IDENTITY, and MySQL rejects
 * AUTO_INCREMENT before the null constraint, so the sequence is
 * type → default → identity → nullability, which all four accept.
 */
function columnClause(engine: DbEngine, column: DesignerColumn): string {
  const parts = [`${quoteSqlIdentifier(engine, column.name)} ${column.dataType}`];

  if (isSqliteRowidKey(engine, column)) {
    // Nothing else may come between the type and these two words.
    parts.push('PRIMARY KEY AUTOINCREMENT');
    return parts.join(' ');
  }

  if (column.defaultValue != null && column.defaultValue !== '') {
    parts.push(`DEFAULT ${column.defaultValue}`);
  }
  if (column.autoIncrement) parts.push(autoIncrementClause(engine).trim());
  if (!column.nullable) parts.push('NOT NULL');
  return parts.join(' ');
}

export function buildCreateTable({
  engine,
  table,
  columns,
}: {
  engine: DbEngine;
  table: QualifiedTable | string;
  columns: DesignerColumn[];
}): string {
  assertEngine(engine);
  assertColumns(columns, 'CREATE TABLE');

  const lines = columns.map((column) => `  ${columnClause(engine, column)}`);
  // A SQLite rowid key is already declared inline; repeating it as a
  // table-level constraint is what stops it being the rowid.
  const key = columns.filter(
    (column) => column.primaryKey && !isSqliteRowidKey(engine, column),
  );
  if (key.length) {
    lines.push(
      `  PRIMARY KEY (${key.map((column) => quoteSqlIdentifier(engine, column.name)).join(', ')})`,
    );
  }
  return `CREATE TABLE ${quoteQualifiedTable(engine, table)} (\n${lines.join(',\n')}\n);`;
}

export function buildAddColumn({
  engine,
  table,
  column,
}: {
  engine: DbEngine;
  table: QualifiedTable | string;
  column: DesignerColumn;
}): string {
  assertEngine(engine);
  const target = quoteQualifiedTable(engine, table);
  const clause = columnClause(engine, column);
  switch (engine) {
    // SQL Server's ADD takes no COLUMN keyword, and Oracle wants the list in
    // parentheses even for one column.
    case 'mssql': return `ALTER TABLE ${target} ADD ${clause};`;
    case 'oracle': return `ALTER TABLE ${target} ADD (${clause});`;
    default: return `ALTER TABLE ${target} ADD COLUMN ${clause};`;
  }
}

export function buildDropColumn({
  engine,
  table,
  column,
}: {
  engine: DbEngine;
  table: QualifiedTable | string;
  column: string;
}): string {
  assertEngine(engine);
  return `ALTER TABLE ${quoteQualifiedTable(engine, table)} DROP COLUMN ${quoteSqlIdentifier(engine, column)};`;
}

/**
 * Changes a column's type and nullability.
 *
 * Postgres is the odd one: it has no statement that does both, so this returns
 * two. Emitting only the TYPE half would leave the old nullability in place
 * with nothing to say so.
 */
export function buildAlterColumn({
  engine,
  table,
  column,
}: {
  engine: DbEngine;
  table: QualifiedTable | string;
  column: DesignerColumn;
}): string {
  assertEngine(engine);
  const target = quoteQualifiedTable(engine, table);
  const name = quoteSqlIdentifier(engine, column.name);
  const notNull = column.nullable ? '' : ' NOT NULL';

  switch (engine) {
    case 'mysql':
    case 'mariadb':
      return `ALTER TABLE ${target} MODIFY COLUMN ${name} ${column.dataType}${notNull};`;
    case 'mssql':
      return `ALTER TABLE ${target} ALTER COLUMN ${name} ${column.dataType}${notNull};`;
    case 'oracle':
      return `ALTER TABLE ${target} MODIFY (${name} ${column.dataType}${notNull});`;
    case 'postgres':
      return [
        `ALTER TABLE ${target} ALTER COLUMN ${name} TYPE ${column.dataType};`,
        `ALTER TABLE ${target} ALTER COLUMN ${name} ${column.nullable ? 'DROP' : 'SET'} NOT NULL;`,
      ].join('\n');
    case 'sqlite':
      // SQLite's ALTER TABLE can add, rename and drop a column, and nothing
      // else. Changing a type or a NOT NULL means creating a new table,
      // copying the rows and swapping the names — which is a data migration,
      // not a statement, and not something to generate behind a checkbox.
      throw new Error(
        'SQLite cannot change a column\'s type or nullability. '
        + 'That needs a table rebuild: create the new table, copy the rows across, then rename.',
      );
    default:
      throw new Error(`Unsupported engine: ${engine}`);
  }
}

/**
 * SQL Server renames through sp_rename, whose arguments are *strings* naming
 * the object — not identifiers — so they are quoted as literals.
 */
function spRenameLiteral(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

export function buildRenameColumn({
  engine,
  table,
  from,
  to,
}: {
  engine: DbEngine;
  table: QualifiedTable | string;
  from: string;
  to: string;
}): string {
  assertEngine(engine);
  const target = typeof table === 'string' ? table : formatQualifiedTable(table);
  if (engine === 'mssql') {
    return `EXEC sp_rename ${spRenameLiteral(`${target}.${from}`)}, ${spRenameLiteral(to)}, 'COLUMN';`;
  }
  return `ALTER TABLE ${quoteQualifiedTable(engine, table)} RENAME COLUMN `
    + `${quoteSqlIdentifier(engine, from)} TO ${quoteSqlIdentifier(engine, to)};`;
}

export function buildRenameTable({
  engine,
  table,
  to,
}: {
  engine: DbEngine;
  table: QualifiedTable | string;
  /** The new bare name; the table stays in the schema it is already in. */
  to: string;
}): string {
  assertEngine(engine);
  const source = typeof table === 'string'
    ? { name: table } as QualifiedTable
    : table;

  switch (engine) {
    case 'mysql':
    case 'mariadb':
      // MySQL's ALTER TABLE ... RENAME exists but RENAME TABLE is the form
      // that takes a qualified target, which is what keeps it in its schema.
      return `RENAME TABLE ${quoteQualifiedTable(engine, source)} TO `
        + `${quoteQualifiedTable(engine, { schema: source.schema, name: to })};`;
    case 'mssql':
      return `EXEC sp_rename ${spRenameLiteral(formatQualifiedTable(source))}, ${spRenameLiteral(to)};`;
    default:
      // Postgres and Oracle take a bare new name and keep the schema.
      return `ALTER TABLE ${quoteQualifiedTable(engine, source)} RENAME TO ${quoteSqlIdentifier(engine, to)};`;
  }
}

export function buildDropTable({
  engine,
  table,
  ifExists,
}: {
  engine: DbEngine;
  table: QualifiedTable | string;
  ifExists?: boolean;
}): string {
  assertEngine(engine);
  // Oracle has no IF EXISTS on DROP TABLE; emitting it is a syntax error, so
  // the guard is silently dropped rather than producing SQL that cannot run.
  const guard = ifExists && engine !== 'oracle' ? 'IF EXISTS ' : '';
  return `DROP TABLE ${guard}${quoteQualifiedTable(engine, table)};`;
}

export function buildCreateIndex({
  engine,
  table,
  name,
  columns,
  unique,
}: {
  engine: DbEngine;
  table: QualifiedTable | string;
  name: string;
  columns: string[];
  unique?: boolean;
}): string {
  assertEngine(engine);
  assertColumns(columns, 'CREATE INDEX');
  const cols = columns.map((column) => quoteSqlIdentifier(engine, column)).join(', ');
  return `CREATE ${unique ? 'UNIQUE ' : ''}INDEX ${quoteSqlIdentifier(engine, name)} `
    + `ON ${quoteQualifiedTable(engine, table)} (${cols});`;
}

export function buildDropIndex({
  engine,
  table,
  name,
}: {
  engine: DbEngine;
  table: QualifiedTable | string;
  name: string;
}): string {
  assertEngine(engine);
  switch (engine) {
    case 'mysql':
    case 'mariadb':
    case 'mssql':
      // Index names are scoped to the table on these two, so the table is
      // part of the statement rather than part of the name.
      return `DROP INDEX ${quoteSqlIdentifier(engine, name)} ON ${quoteQualifiedTable(engine, table)};`;
    default: {
      // Postgres and Oracle scope index names to the schema, like tables.
      const schema = typeof table === 'string' ? undefined : table.schema;
      return `DROP INDEX ${quoteQualifiedTable(engine, { schema, name })};`;
    }
  }
}
