import assert from 'node:assert/strict';
import test from 'node:test';
import type { DbEngine } from '../models';
import {
  buildAddColumn,
  buildAlterColumn,
  buildCreateIndex,
  buildCreateTable,
  buildDropColumn,
  buildDropIndex,
  buildDropTable,
  buildRenameColumn,
  buildRenameTable,
} from './tableDesignerSql';

const ENGINES: DbEngine[] = ['mysql', 'postgres', 'mssql', 'oracle'];
const t = { schema: 'app', name: 'patients' };

// ── CREATE TABLE ────────────────────────────────────────────────────────────

test('a table is created with its columns in the given order', () => {
  const sql = buildCreateTable({
    engine: 'postgres',
    table: { name: 'patients' },
    columns: [
      { name: 'id', dataType: 'integer', nullable: false },
      { name: 'name', dataType: 'text', nullable: true },
    ],
  });
  assert.equal(
    sql,
    'CREATE TABLE "patients" (\n  "id" integer NOT NULL,\n  "name" text\n);',
  );
});

test('the schema is carried into CREATE TABLE', () => {
  const sql = buildCreateTable({
    engine: 'postgres', table: t,
    columns: [{ name: 'id', dataType: 'integer', nullable: false }],
  });
  assert.match(sql, /CREATE TABLE "app"\."patients"/);
});

test('a primary key becomes a table-level constraint', () => {
  const sql = buildCreateTable({
    engine: 'mysql',
    table: { name: 'visit_meds' },
    columns: [
      { name: 'visit_id', dataType: 'int', nullable: false, primaryKey: true },
      { name: 'med_id', dataType: 'int', nullable: false, primaryKey: true },
    ],
  });
  assert.match(sql, /PRIMARY KEY \(`visit_id`, `med_id`\)/);
});

test('auto-increment is spelled the way each engine spells it', () => {
  const column = { name: 'id', dataType: 'int', nullable: false, primaryKey: true, autoIncrement: true };
  const of = (engine: DbEngine) => buildCreateTable({ engine, table: { name: 't' }, columns: [column] });
  assert.match(of('mysql'), /AUTO_INCREMENT/);
  assert.match(of('mssql'), /IDENTITY\(1,1\)/);
  assert.match(of('postgres'), /GENERATED BY DEFAULT AS IDENTITY/);
  assert.match(of('oracle'), /GENERATED BY DEFAULT AS IDENTITY/);
});

test('a default is interpolated as the expression it is, not as a string', () => {
  // Defaults are expressions: CURRENT_TIMESTAMP and 0 are not the text of
  // themselves. Quoting them would store the literal words.
  const sql = buildCreateTable({
    engine: 'postgres',
    table: { name: 't' },
    columns: [{ name: 'created', dataType: 'timestamptz', nullable: false, defaultValue: 'now()' }],
  });
  assert.match(sql, /"created" timestamptz DEFAULT now\(\) NOT NULL/);
});

test('a table with no columns is refused', () => {
  assert.throws(
    () => buildCreateTable({ engine: 'mysql', table: { name: 't' }, columns: [] }),
    /at least one column/i,
  );
});

// ── ALTER: add / drop / change ──────────────────────────────────────────────

test('adding a column uses the keyword each engine accepts', () => {
  const column = { name: 'notes', dataType: 'text', nullable: true };
  assert.equal(
    buildAddColumn({ engine: 'postgres', table: t, column }),
    'ALTER TABLE "app"."patients" ADD COLUMN "notes" text;',
  );
  // SQL Server has no COLUMN keyword here, and Oracle wants the parentheses.
  assert.equal(
    buildAddColumn({ engine: 'mssql', table: t, column }),
    'ALTER TABLE [app].[patients] ADD [notes] text;',
  );
  assert.equal(
    buildAddColumn({ engine: 'oracle', table: t, column }),
    'ALTER TABLE "app"."patients" ADD ("notes" text);',
  );
});

test('dropping a column names it as an identifier', () => {
  for (const engine of ENGINES) {
    const sql = buildDropColumn({ engine, table: t, column: 'order' });
    assert.match(sql, /DROP COLUMN/, engine);
    assert.ok(/[`"[]order[`"\]]/.test(sql), `${engine} left the name unquoted: ${sql}`);
  }
});

test('changing a column type is one statement per engine dialect', () => {
  const column = { name: 'dose', dataType: 'numeric(6,2)', nullable: false };
  assert.equal(
    buildAlterColumn({ engine: 'mysql', table: t, column }),
    'ALTER TABLE `app`.`patients` MODIFY COLUMN `dose` numeric(6,2) NOT NULL;',
  );
  assert.equal(
    buildAlterColumn({ engine: 'mssql', table: t, column }),
    'ALTER TABLE [app].[patients] ALTER COLUMN [dose] numeric(6,2) NOT NULL;',
  );
  assert.equal(
    buildAlterColumn({ engine: 'oracle', table: t, column }),
    'ALTER TABLE "app"."patients" MODIFY ("dose" numeric(6,2) NOT NULL);',
  );
});

test('Postgres splits a column change into type and nullability', () => {
  // Postgres has no single statement that does both, and running only the
  // TYPE half would silently leave the old nullability in place.
  const sql = buildAlterColumn({
    engine: 'postgres', table: t,
    column: { name: 'dose', dataType: 'numeric(6,2)', nullable: false },
  });
  assert.match(sql, /ALTER COLUMN "dose" TYPE numeric\(6,2\);/);
  assert.match(sql, /ALTER COLUMN "dose" SET NOT NULL;/);
});

test('making a Postgres column nullable drops the constraint rather than setting it', () => {
  const sql = buildAlterColumn({
    engine: 'postgres', table: t,
    column: { name: 'dose', dataType: 'numeric', nullable: true },
  });
  assert.match(sql, /DROP NOT NULL;/);
});

// ── renames ─────────────────────────────────────────────────────────────────

test('renaming a column uses sp_rename on SQL Server and RENAME COLUMN elsewhere', () => {
  assert.equal(
    buildRenameColumn({ engine: 'postgres', table: t, from: 'a', to: 'b' }),
    'ALTER TABLE "app"."patients" RENAME COLUMN "a" TO "b";',
  );
  assert.equal(
    buildRenameColumn({ engine: 'mssql', table: t, from: 'a', to: 'b' }),
    `EXEC sp_rename 'app.patients.a', 'b', 'COLUMN';`,
  );
});

test('renaming a table follows each engine, and MySQL uses RENAME TABLE', () => {
  assert.equal(
    buildRenameTable({ engine: 'mysql', table: t, to: 'people' }),
    'RENAME TABLE `app`.`patients` TO `app`.`people`;',
  );
  assert.equal(
    buildRenameTable({ engine: 'postgres', table: t, to: 'people' }),
    'ALTER TABLE "app"."patients" RENAME TO "people";',
  );
  assert.equal(
    buildRenameTable({ engine: 'mssql', table: t, to: 'people' }),
    `EXEC sp_rename 'app.patients', 'people';`,
  );
});

// ── DROP TABLE ──────────────────────────────────────────────────────────────

test('dropping a table names it in full', () => {
  assert.equal(buildDropTable({ engine: 'postgres', table: t }), 'DROP TABLE "app"."patients";');
});

test('Oracle has no IF EXISTS, so it is not offered there', () => {
  assert.equal(
    buildDropTable({ engine: 'postgres', table: t, ifExists: true }),
    'DROP TABLE IF EXISTS "app"."patients";',
  );
  assert.equal(
    buildDropTable({ engine: 'oracle', table: t, ifExists: true }),
    'DROP TABLE "app"."patients";',
  );
});

// ── indexes ─────────────────────────────────────────────────────────────────

test('an index is created over its columns in order', () => {
  assert.equal(
    buildCreateIndex({ engine: 'postgres', table: t, name: 'ix_name', columns: ['last', 'first'] }),
    'CREATE INDEX "ix_name" ON "app"."patients" ("last", "first");',
  );
});

test('a unique index says so', () => {
  assert.match(
    buildCreateIndex({ engine: 'mysql', table: t, name: 'ux', columns: ['email'], unique: true }),
    /^CREATE UNIQUE INDEX/,
  );
});

test('an index with no columns is refused', () => {
  assert.throws(
    () => buildCreateIndex({ engine: 'mysql', table: t, name: 'ix', columns: [] }),
    /at least one column/i,
  );
});

test('dropping an index needs the table on MySQL and SQL Server', () => {
  // Postgres and Oracle index names are schema-scoped; MySQL and SQL Server
  // scope them to the table, so the statement is shaped differently.
  assert.equal(
    buildDropIndex({ engine: 'mysql', table: t, name: 'ix' }),
    'DROP INDEX `ix` ON `app`.`patients`;',
  );
  assert.equal(
    buildDropIndex({ engine: 'mssql', table: t, name: 'ix' }),
    'DROP INDEX [ix] ON [app].[patients];',
  );
  assert.equal(
    buildDropIndex({ engine: 'postgres', table: t, name: 'ix' }),
    'DROP INDEX "app"."ix";',
  );
  assert.equal(
    buildDropIndex({ engine: 'oracle', table: t, name: 'ix' }),
    'DROP INDEX "app"."ix";',
  );
});

// ── injection ───────────────────────────────────────────────────────────────

test('every name goes through identifier quoting', () => {
  for (const engine of ENGINES) {
    const sql = buildAddColumn({
      engine,
      table: { name: 'x`"];--' },
      column: { name: 'y`"];--', dataType: 'int', nullable: true },
    });
    // Whatever the payload, it must come out as one quoted identifier each.
    assert.ok(!/;\s*DROP/i.test(sql), `${engine} let a statement break out: ${sql}`);
  }
});

// ── SQLite ──────────────────────────────────────────────────────────────────
//
// SQLite's ALTER TABLE does far less than the others: it can add, rename and
// (since 3.35) drop a column, and rename the table. It cannot change a
// column's type or nullability at all — that needs a full table rebuild.

test('SQLite adds a column with the standard spelling', () => {
  assert.equal(
    buildAddColumn({
      engine: 'sqlite', table: { name: 'patients' },
      column: { name: 'notes', dataType: 'TEXT', nullable: true },
    }),
    'ALTER TABLE "patients" ADD COLUMN "notes" TEXT;',
  );
});

test('SQLite renames a column and a table like Postgres does', () => {
  assert.equal(
    buildRenameColumn({ engine: 'sqlite', table: { name: 't' }, from: 'a', to: 'b' }),
    'ALTER TABLE "t" RENAME COLUMN "a" TO "b";',
  );
  assert.equal(
    buildRenameTable({ engine: 'sqlite', table: { name: 't' }, to: 'u' }),
    'ALTER TABLE "t" RENAME TO "u";',
  );
});

// Emitting a statement SQLite rejects would fail at the server with a syntax
// error the user cannot act on; saying so here names the actual limitation.
test('changing a SQLite column type is refused with the reason', () => {
  assert.throws(
    () => buildAlterColumn({
      engine: 'sqlite', table: { name: 't' },
      column: { name: 'a', dataType: 'TEXT', nullable: true },
    }),
    /SQLite[\s\S]*rebuild/i,
  );
});

test('SQLite auto-increment is the rowid alias, not a keyword of its own', () => {
  const sql = buildCreateTable({
    engine: 'sqlite',
    table: { name: 't' },
    columns: [{ name: 'id', dataType: 'INTEGER', nullable: false, primaryKey: true, autoIncrement: true }],
  });
  // INTEGER PRIMARY KEY is the alias for rowid; a separate PRIMARY KEY clause
  // would stop it being one, and AUTOINCREMENT is only legal inline.
  assert.match(sql, /"id" INTEGER PRIMARY KEY AUTOINCREMENT/);
  assert.ok(!/PRIMARY KEY \("id"\)/.test(sql), 'no second, table-level key');
});

test('SQLite drops an index by name alone', () => {
  assert.equal(
    buildDropIndex({ engine: 'sqlite', table: { name: 't' }, name: 'ix' }),
    'DROP INDEX "ix";',
  );
});
